# Generated by Django 4.2.2 on 2023-06-30 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd'), ('post_doc', 'post_doc'), ('jd', 'jd')], max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('in_progress', 'in_progress')], default='in_progress', max_length=255)),
                ('obtained_gpa', models.CharField(blank=True, max_length=255, null=True)),
                ('total_gpa', models.CharField(blank=True, max_length=255, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='user.course')),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Interest', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Univeristy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_uni_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_uni_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('premium', 'premium')], default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('imgage', models.ImageField(blank=True, null=True, upload_to=user.models.upload_image_path)),
                ('uni_id', models.ImageField(blank=True, null=True, upload_to=user.models.upload_image_path)),
                ('resume', models.FileField(blank=True, null=True, upload_to=user.models.upload_image_path)),
                ('google_scholar_page', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('research_background', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('want_to_supervise', models.BooleanField(default=False)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('student', 'student'), ('professor', 'professor')], default='student', max_length=10)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.degree')),
                ('degree_seeking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_seeking', to='user.degree_level')),
                ('interests', models.ManyToManyField(blank=True, to='user.interest')),
                ('publications', models.ManyToManyField(blank=True, to='user.publication')),
                ('research_area', models.ManyToManyField(blank=True, related_name='research_area', to='user.interest')),
                ('student_interest_level', models.ManyToManyField(blank=True, to='user.degree_level')),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.degree_level')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.univeristy')),
            ],
        ),
    ]
