# Generated by Django 4.2.2 on 2023-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_degree_courses_remove_domain_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
