# Generated by Django 4.2.2 on 2023-06-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_degree_degree_level_interest_publication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
