# Generated by Django 4.2.2 on 2023-07-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_profile_f_name_profile_l_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
