# Generated by Django 4.2.2 on 2023-07-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgage',
            new_name='image',
        ),
    ]
