# Generated by Django 4.2.2 on 2023-07-08 15:19

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_imgage_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('student_mail', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uni_id',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Univeristy',
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='core.university'),
        ),
    ]
