# Generated by Django 4.2.2 on 2023-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_university_remove_profile_uni_id_delete_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.AddField(
            model_name='profile',
            name='degrees',
            field=models.ManyToManyField(blank=True, to='core.degree'),
        ),
    ]
