# Generated by Django 4.2.2 on 2023-07-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_profile_degree_profile_degrees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interests',
            new_name='research_areas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='research_area',
        ),
    ]
