# Generated by Django 4.2.2 on 2023-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_interests_profile_research_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_interest_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd'), ('post_doc', 'post_doc'), ('jd', 'jd')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opening',
            name='level',
            field=models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd'), ('post_doc', 'post_doc'), ('jd', 'jd')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree_seeking',
            field=models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd'), ('post_doc', 'post_doc'), ('jd', 'jd')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Degree_Level',
        ),
    ]
