# Generated by Django 4.2.2 on 2023-07-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_student_interest_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='student_mail',
            new_name='email',
        ),
    ]
