# Generated by Django 4.2.2 on 2023-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_student_mail_university_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('id', 'id')], max_length=255, null=True),
        ),
    ]
