# Generated by Django 4.2.2 on 2023-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_university_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uni_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
