# Generated by Django 4.2.2 on 2023-07-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_uni_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='degree',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='major',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='courses',
        ),
        migrations.AddField(
            model_name='degree',
            name='courses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
