# Generated by Django 4.2.2 on 2023-07-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_degree_degree_name_remove_degree_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='research_areas',
        ),
        migrations.AddField(
            model_name='profile',
            name='research_areas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
